# Billharz.com (Jekyll/Github Pages)
# Switched from self-hosted to GH Pages/Netlify

# Error Fixes
# Github Metadata plugin requires API key https://github.com/github/pages-gem/issues/399#issuecomment-361091215
repository: richpeck/billharz # Required for Netlify

# General
# Give us the ability to manage the overall structuer of the site etc
title:    Frédéric BILLHARZ (contacts)
keywords: frederic, billharz, tenor, singer, contacts
author:   Frédéric Billharz
url:      https://www.billharz.com # required for sitemap (https://github.com/jekyll/jekyll-sitemap#usage)

# System
# Overall options for the entire site
locale:   fr_CH
timezone: Europe/Zurich

# Google Analytics
google_analytics: UA-121708314-2

# Exclude
# Exclude these files from the build.
exclude:
  - .github
  - .editorconfig
  - .gitignore
  - _config.yml
  - CHANGELOG.md
  - CODE_OF_CONDUCT.md
  - config.ru
  - CONTRIBUTING.md
  - LICENSE
  - Procfile
  - Rakefile
  - README.md
  - static.json

# Include
# Includes extra files etc
include: 
  - _pages

# Plugins
# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#plugins 
plugins:
  - jekyll-feed # https://github.com/jekyll/jekyll-feed
  - jekyll-seo-tag # https://github.com/jekyll/jekyll-seo-tag
  - jekyll-sitemap # https://github.com/jekyll/jekyll-sitemap
  - jekyll-last-modified-at # https://github.com/gjtorikian/jekyll-last-modified-at
  - jekyll-minifier # https://github.com/digitalsparky/jekyll-minifier

# Defaults
# Allows us to define different elements for the site from within the config file
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true