###################
###################

## Jekyll Build ##
## Due to Netlify changing its system, decided to host our Jekyll sites ourselves ##

## This builds the jekyll site inside Ubuntu and allows us to push the result to our server via SSH ##

###################
###################

## Name ##
## Builds Jekyll sites on push (locally) and then sends the compiled payload to our server ##
name: Jekyll Build

## Push ##
## Only trigger when 'main' branch is updated ##
on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

## Jobs ##
## Basically need to install Ruby, Jekyll, Bundler and run the build as required ##
jobs:

  ## Build ##
  ## Single job to install Jekyll and run it ##
  build:
  
    ## OS ##
    runs-on: ubuntu-latest

    ## Steps ##
    ## Required to complete the job ##
    steps:
    
      ## Repo ##
      ## Pulls the latest files for the repo ##
      - uses: actions/checkout@v3
      
      ## Jekyll ##
      ## Builds Jekyll ##
      - name: Build
        uses: actions/jekyll-build-pages@v1
        
      ## Release ##
      ## Create release of Jekyll site so that we're able to reference it as needed in the future ##
      #- name: Deploy files via FTP
      #  uses: SamKirkland/FTP-Deploy-Action@4.3.0
      #  with:
      #    server:       ${{ secrets.FTP_SERVER }}
      #    username:     ${{ secrets.FTP_USERNAME }}
      #    password:     ${{ secrets.FTP_PASSWORD }} 
      #    local-dir:    ${{ github.workspace }}/_site/
      #    server-dir:   ${{ secrets.FTP_DIRECTORY }}

      ## Release ##
      ## Create release of Jekyll site so that we're able to reference it as needed in the future ##
      - uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
        with:
          ftp_host:         ${{ secrets.FTP_SERVER }}
          ftp_username:     ${{ secrets.FTP_USERNAME }}
          ftp_password:     ${{ secrets.FTP_PASSWORD }}
          local_source_dir: './_site/'
          dist_target_dir:  ${{ secrets.FTP_DIRECTORY }}
          delete:           'true'
